[build]
base = "netlify"
publish = "public"
command = "sed -i 's/depth: 1/depth: undefined/g' node_modules/@antora/content-aggregator/lib/aggregate-content.js && node_modules/.bin/antora --html-url-extension-style=indexify --pull ../antora-playbook.yml"

[build.environment]
NODE_VERSION = "10"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

#[context.production.environment]
#ALGOLIA_API_KEY = "..."
#ALGOLIA_INDEX_NAME = "asciidoctor"
#GOOGLE_ANALYTICS_KEY = "..."

[context.deploy-preview]
command = "sed -i 's/depth: 1/depth: undefined/g' node_modules/@antora/content-aggregator/lib/aggregate-content.js && node_modules/.bin/antora --html-url-extension-style=indexify --pull --url $DEPLOY_PRIME_URL ../antora-playbook.yml"

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"
