name: Index
on: [workflow_dispatch]
#on:
#  schedule:
#  - cron: '15 4 * * *'
#on:
#  push:
#    branches:
#    - main
jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'asciidoctor/docs.asciidoctor.org' &&
      !endsWith(github.event.head_commit.message, ' [skip ci]')
    steps:
    - run: echo ok go
  build:
    needs: activate
    runs-on: ubuntu-latest
    container: algolia/docsearch-scraper:v1.12.0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run indexer
      env:
        APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
        API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        CONFIG: ${{ github.workspace }}/docsearch/config.json
        UPDATE_NB_HITS: 'false'
      run: |
        echo ${{ github.event_name }}
        #export HOME=/root
        #export INDEX_NAME_TMP=$(node -p "JSON.parse(require('fs').readFileSync('$CONFIG')).index_name")_tmp-$GITHUB_RUN_ID
        #cd $HOME
        #pipenv run python -m src.index
