name: Nightly Build Trigger
on:
  schedule:
  - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Ping Netlify Webhook
      run: |
        echo ok go
      #run: |
      #  curl -X POST -d '' -s ${{ secrets.NETLIFY_BUILD_HOOK }}
